version: '2.2'
services:
  keycloak-lokaal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: "ictu"
      KEYCLOAK_ADMIN_PASSWORD: "ictu"
    volumes:
      - ./keycloak/:/opt/keycloak/data/import/
    logging:
      driver: gelf
      options:
        gelf-address: "udp://0.0.0.0:12201"
        tag: "log-keycloak-tag-docker"
    ports:
      - "8080:8080"
      - "8443:8443"

networks:
  elastic:
    name: elastic
    driver: bridge

