version: '2.2'
services:
  keycloak-lokaal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: "ictu"
      KEYCLOAK_ADMIN_PASSWORD: "ictu"
    volumes:
      - ./keycloak/:/opt/keycloak/data/import/
    logging:
      driver: gelf
      options:
        gelf-address: "udp://0.0.0.0:12201"
        tag: "log-keycloak-tag-docker"
    ports:
      - "9999:8080"
      - "8443:8443"

  keycloak-ad1:
    image: quay.io/keycloak/keycloak:20.0.1
    container_name: keycloak_ad1
    command:
      - start-dev
      - '--import-realm'
    volumes:
      - ./keycloak/fake-digid/realms/:/opt/keycloak/data/import/
      - ./keycloak/fake-digid/theme/:/opt/keycloak/themes/fakedigid/
    environment:
      - KEYCLOAK_ADMIN=ictu
      - KEYCLOAK_ADMIN_PASSWORD=ictu
      - KC_PROXY=edge
    ports:
      - "9090:8080"

  keycloak-dv1:
    image: quay.io/keycloak/keycloak:20.0.1
    container_name: keycloak_dv1
    command:
      - start-dev
      - '--import-realm'
    volumes:
      - ./keycloak/lutjebroek/:/opt/keycloak/data/import/
    environment:
      - KEYCLOAK_ADMIN=ictu
      - KEYCLOAK_ADMIN_PASSWORD=ictu
      - KC_PROXY=edge
    ports:
      - "9091:8080"

